[metadata]
name = anonym-pseudonym
version = 0.2.0
author = Moustapha Kebe
author_email = moustapha.kebe@paris.fr
description = Anonymisation avancée de DataFrames pandas avec support NER optionnel
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/moustaphak.../anonymizer
project_urls =
    Bug Tracker = https://github.com/moustaphak..
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Intended Audience :: Developers
    Topic :: Text Processing

[options]
packages = find:
package_dir =
    = src
python_requires = >=3.8
install_requires =
    pandas>=1.5.0
    tqdm>=4.65.0
    transformers>=4.57.1
    tokenizers<=0.23.0
    protobuf

[options.packages.find]
where = src

[options.package_data]
* = *.txt, *.md

[options.extras_require]
ner =
    transformers>=4.57.1
    torch
dev =
    pytest>=7.0
    black>=23.0
    flake8>=6.0

# Si vous voulez une commande CLI (optionnel)
# [options.entry_points]
# console_scripts =
#     anonymizer = Anonymizer.anonymer:main