[metadata]
name = cv-recommendation

[options]
packages = find:
package_dir =
    = src

install_requires =
    pandas
    numpy
    scikit-learn
    pymupdf
    fpdf
    sentence_transformers

[options.extras_require]
dev=
    pytest
    sphinx
vis=
    matplotlib  

[options.packages.find]
where = src

[options.package_data]
* = *.txt